# Homebrew cask for the arpwal/homebrew-tap repository.
# Generated by scripts/update-cask.sh; do not edit the version or sha256 by hand.
cask "leftovers" do
  version "1.3.0"
  sha256 "e6db64e1d80a6aaebc93f02f8410751b29b39aecf57ecbafcafa689a5eae5e6f"

  url "https://github.com/arpwal/leftovers/releases/download/v#{version}/Leftovers.dmg"
  name "Leftovers"
  desc "Menu-bar app that cleans up what apps and coding agents left running"
  homepage "https://arpwal.github.io/leftovers/"

  depends_on macos: :sonoma

  app "Leftovers.app"

  zap trash: "~/Library/Preferences/com.arpwal.leftovers.plist"
end
