# Homebrew cask for the arpwal/homebrew-tap repository.
# Generated by scripts/update-cask.sh; do not edit the version or sha256 by hand.
cask "leftovers" do
  version "1.1.3"
  sha256 "2e7e2946e493b90ba955054993205756e3c56b024060b442627635d92ce0ca89"

  url "https://github.com/arpwal/leftovers/releases/download/v#{version}/Leftovers.dmg"
  name "Leftovers"
  desc "Menu-bar app that cleans up what apps and coding agents left running"
  homepage "https://arpwal.github.io/leftovers/"

  depends_on macos: :sonoma

  app "Leftovers.app"

  zap trash: "~/Library/Preferences/com.arpwal.leftovers.plist"
end
