# Homebrew cask for the arpwal/homebrew-tap repository.
# Generated by scripts/update-cask.sh; do not edit the version or sha256 by hand.
cask "leftovers" do
  version "1.8.0"
  sha256 "f10c0da449fd635d30f19f7888b099c961b78cb4eca481784fe65086bb9bd634"

  url "https://github.com/arpwal/leftovers/releases/download/v#{version}/Leftovers.dmg"
  name "Leftovers"
  desc "Menu-bar app that cleans up what apps and coding agents left running"
  homepage "https://arpwal.github.io/leftovers/"

  depends_on macos: :sonoma

  app "Leftovers.app"

  zap trash: "~/Library/Preferences/com.arpwal.leftovers.plist"
end
